resources:
  - deploy.yaml
  - service.yaml
  - >-
    github.com/partiallyordered/bases/mysql?ref=01e9909a2bfc040dac27bb770f79a1049d833bda
secretGenerator:
  - name: connection-manager-api-api-secret
    literals:
      - dummy=DUMMY
  - name: mysql
    behavior: merge
    literals:
      - MYSQL_PASSWORD=mcm
      - MYSQL_ROOT_PASSWORD=mcm
configMapGenerator:
  - name: mysql
    behavior: merge
    literals:
      - MYSQL_SERVICE=mysql
      - MYSQL_USER=mcm
      - MYSQL_DATABASE=mcm
  - name: connection-manager-api
    files:
      - EMBEDDED_CERTIFICATE=secrets/embedded.cert
    literals:
      - AUTH_ENABLED=false
      - APP_OAUTH_CLIENT_KEY=crdmiD6t43bvveEmEgcK8IRffwka
      - APP_OAUTH_CLIENT_SECRET=5sEefrRpfFpHkPS92ip5irJw5_oa
      - OAUTH2_ISSUER=https://iskm.workbench.mbox-dev.io:9543/oauth2/token
      - OAUTH2_TOKEN_ISS=https://iskm.workbench.mbox-dev.io:9443/oauth2/token
      - JWT_COOKIE_NAME=MCM-API_ACCESS_TOKEN
      - OAUTH_RESET_PASSWORD_ISSUER=https://localhost:6000/oauth2/token
      - OAUTH_RESET_PASSWORD_AUTH_USER=user
      - OAUTH_RESET_PASSWORD_AUTH_PASSWORD=password
      - EXTRA_CERTIFICATE_CHAIN_FILE_NAME=
      - EXTRA_ROOT_CERT_FILE_NAME=
      - AUTH_2FA=false
      - AUTH_2FA_ENABLED=false
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mcm
      - DATABASE_SCHEMA=mcm
      - DB_RETRIES=100
      - DB_CONNECTION_RETRY_WAIT_MILLISECONDS=5000
      - RUN_MIGRATIONS=true
      - VAULT_AUTH_METHOD=APP_ROLE
      - VAULT_ROLE_ID_FILE=/vault/secrets/role-id
      - VAULT_ROLE_SECRET_ID_FILE=/vault/secrets/secret-id
      - VAULT_ENDPOINT=http://vault:8200
      - VAULT_PKI_BASE_DOMAIN=example.com
