apiVersion: v1
kind: Service
metadata:
  name: connection-manager-api
  labels:
    app.kubernetes.io/name: connection-manager-api
spec:
  type: "NodePort"
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
    nodePort: 31057
  selector:
    app.kubernetes.io/name: connection-manager-api
