const {
  API_BASE_URL,
  AUTH_ENABLED,
  UI_OIDC_LOGIN_REDIRECT_URL,
  OIDC_TOKEN_PROVIDER_URL,
  OIDC_CLIENT_ID,
  OIDC_CLIENT_SECRET,
  MCM_COOKIE_NAME = 'MCM_SESSION',
  HTTP_PORT = 8080,
} = process.env;
// validate required env vars

module.exports = {
  API_BASE_URL,
  AUTH_ENABLED,
  UI_OIDC_LOGIN_REDIRECT_URL,
  OIDC_TOKEN_PROVIDER_URL,
  OIDC_CLIENT_ID,
  OIDC_CLIENT_SECRET,
  MCM_COOKIE_NAME,
  HTTP_PORT,
};
