apiVersion: v1
kind: Service
metadata:
  name: connection-manager-ui
  labels:
    app.kubernetes.io/name: connection-manager-ui
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app.kubernetes.io/name: connection-manager-ui
